/*
Thu Jan 14 2021 10:39:46 GMT+0200 (за східноєвропейським стандартним часом)
__proto__:
constructor: ƒ Date()
getDate: ƒ getDate()
getDay: ƒ getDay()
getFullYear: ƒ getFullYear()
getHours: ƒ getHours()
getMilliseconds: ƒ getMilliseconds()
getMinutes: ƒ getMinutes()
getMonth: ƒ getMonth()
getSeconds: ƒ getSeconds()
getTime: ƒ getTime()
getTimezoneOffset: ƒ getTimezoneOffset()
getUTCDate: ƒ getUTCDate()
getUTCDay: ƒ getUTCDay()
getUTCFullYear: ƒ getUTCFullYear()
getUTCHours: ƒ getUTCHours()
getUTCMilliseconds: ƒ getUTCMilliseconds()
getUTCMinutes: ƒ getUTCMinutes()
getUTCMonth: ƒ getUTCMonth()
getUTCSeconds: ƒ getUTCSeconds()
getYear: ƒ getYear()
setDate: ƒ setDate()
setFullYear: ƒ setFullYear()
setHours: ƒ setHours()
setMilliseconds: ƒ setMilliseconds()
setMinutes: ƒ setMinutes()
setMonth: ƒ setMonth()
setSeconds: ƒ setSeconds()
setTime: ƒ setTime()
setUTCDate: ƒ setUTCDate()
setUTCFullYear: ƒ setUTCFullYear()
setUTCHours: ƒ setUTCHours()
setUTCMilliseconds: ƒ setUTCMilliseconds()
setUTCMinutes: ƒ setUTCMinutes()
setUTCMonth: ƒ setUTCMonth()
setUTCSeconds: ƒ setUTCSeconds()
setYear: ƒ setYear()
toDateString: ƒ toDateString()
toGMTString: ƒ toUTCString()
toISOString: ƒ toISOString()
toJSON: ƒ toJSON()
toLocaleDateString: ƒ toLocaleDateString()
toLocaleString: ƒ toLocaleString()
toLocaleTimeString: ƒ toLocaleTimeString()
toString: ƒ toString()
toTimeString: ƒ toTimeString()
toUTCString: ƒ toUTCString()
valueOf: ƒ valueOf()
Symbol(Symbol.toPrimitive): ƒ [Symbol.toPrimitive]()
__proto__: Object
*/

// moment library = moment.(date).format(yy/mm/dd)
const date = new Date ()
console.dir(date);

date.setFullYear(3000);
console.dir(date);

